document:
  name: "Tourism Digital Hub - Linee Guida sull'Interoperabilità"
  description: "Questo documento si pone come base di riferimento per l’Interoperabilità che il Ministero del Turismo intende adottare nei confronti di Operatori Istituzionali e Privati, per lo scambio di informazioni, dati e servizi con il Tourism Digital Hub (TDH), iniziativa collegata al PNRR che ha come fine la promozione dell’offerta turistica verso il mercato interno e internazionale."
  tags:
    - turismo
